#!/bin/bash

docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /etc:/etc:ro -e FORCE_IMAGE_REMOVAL=1 -e FORCE_CONTAINER_REMOVAL=1 -e MINIMUM_IMAGES_TO_SAVE=1 spotify/docker-gc

docker rmi -f $(docker images | grep "<none>" | awk "{print $3}")